name: dart_ipfs_api
version: 0.0.1
description: >-
  A client that communicates with ipfs_companion to access ipfs
repository:
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http:

dev_dependencies:
